import type { VercelRequest, VercelResponse } from "@vercel/node";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { verifyToken } from "../../lib/auth.js";

const bodySchema = z.object({
    targetUrl: z.string().url("Must be a valid URL"),
    companyName: z.string().min(2),
    industry: z.string().optional(),
});

const getAnthropicApiKey = async () => {
    const settings = await prisma.setting.findMany({
        where: { key: { in: ["CLAUDE_API_KEY", "ANTHROPIC_API_KEY"] } },
    });
    const map = new Map(settings.map((item) => [item.key, item.value]));
    return String(map.get("CLAUDE_API_KEY") || map.get("ANTHROPIC_API_KEY") || process.env.CLAUDE_API_KEY || process.env.ANTHROPIC_API_KEY || "").trim();
};

export default async function handler(req: VercelRequest, res: VercelResponse) {
    if (req.method !== "POST") return res.status(405).end();

    // Basic auth check
    let user: any;
    try {
        user = await verifyToken(req);
    } catch (err: any) {
        return res.status(401).json({ error: "Unauthorized" });
    }

    const parsed = bodySchema.safeParse(req.body);
    if (!parsed.success) {
        return res.status(400).json({ error: "Invalid payload", details: parsed.error.flatten() });
    }

    const { targetUrl, companyName, industry } = parsed.data;

    try {
        const apiKey = await getAnthropicApiKey();
        if (!apiKey) {
            return res.status(500).json({ error: "Anthropic API key missing in Admin Settings." });
        }

        const prompt = `You are an expert SEO sales specialist acting on behalf of InstantSEOScan. Your goal is to write a highly personalized, compelling cold outreach email to a potential client offering a free SEO audit.

Client Details:
- Company Name: ${companyName}
- Website: ${targetUrl}
- Industry: ${industry || "General"}

Instructions:
1. Write a catchy subject line.
2. Draft a short, concise, and professional cold email (max 150 words).
3. Mention that you ran a quick preliminary SEO check on their website and noticed a few opportunities that could help improve their Google rankings (e.g. missing meta descriptions, weak internal linking, page speed).
4. Offer them a free, in-depth SEO report generated by InstantSEOScan.
5. End with a polite call to action asking if they'd be open to seeing the report.
6. Sign off as the "InstantSEOScan Growth Team".

Return the output in STRICT JSON format like so:
{
  "subject": "The email subject line here",
  "body": "The main email body text here. Use \\n for newlines."
}`;

        const response = await fetch("https://api.anthropic.com/v1/messages", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "x-api-key": apiKey,
                "anthropic-version": "2023-06-01",
            },
            body: JSON.stringify({
                model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-20250514",
                max_tokens: 800,
                temperature: 0.7,
                messages: [{ role: "user", content: prompt }],
            }),
        });

        if (!response.ok) {
            const text = await response.text();
            throw new Error(text || `Anthropic request failed (${response.status})`);
        }

        const payload = await response.json();
        const outputText = Array.isArray(payload?.content)
            ? payload.content.find((chunk: any) => chunk?.type === "text")?.text || ""
            : "";

        let parsedResult;
        try {
            const jsonMatch = outputText.match(/\\{([\\s\\S]*?)\\}/);
            if (jsonMatch) {
                parsedResult = JSON.parse(jsonMatch[0]);
            } else {
                parsedResult = JSON.parse(outputText);
            }
        } catch (e) {
            // Fallback text if json parsing fails
            return res.status(200).json({
                subject: `Quick SEO Improvement Opportunity for ${companyName}`,
                body: outputText
            });
        }

        return res.status(200).json(parsedResult);
    } catch (error: any) {
        console.error("AI Email Generation Error:", error);
        return res.status(500).json({ error: error?.message || "Failed to generate AI email" });
    }
}
